# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11769f57b17591a65da39138208f6f20b04f1b0f44513b382df595761cb22328697e077e99000f8826384f5bd6572e1dbd6056592e05cf8581b5e3311ebb967e

test:
  secret_key_base: c99df67d907d83506bb92bd3710c45fee89d60cef849d2a2eae5e6448b5e4c8b99d10500079c1e30b25507981a25a8ce17364d602596a5121b651bb34363c340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
